"""
Preset dream ideas — curated examples couples can one-click add to their bucket list.
Organized by category name (must match db.DEFAULT_CATEGORIES).
"""

PRESET_IDEAS = {
    "Travel": [
        ("Visit Tokyo together", "🗼"),
        ("Road trip to Goa", "🏖️"),
        ("See the Northern Lights", "🌌"),
        ("Backpack through Europe", "🎒"),
        ("Weekend getaway to the hills", "⛰️"),
        ("Visit Taj Mahal at sunrise", "🕌"),
        ("Bali vacation", "🌴"),
        ("Camping under the stars", "⛺"),
        ("Maldives honeymoon", "🏝️"),
        ("Train ride through Kerala", "🚂"),
    ],
    "Food": [
        ("Try a Michelin-star restaurant", "⭐"),
        ("Cook a 5-course meal together", "🍳"),
        ("Street-food tour of Mumbai", "🌮"),
        ("Bake a cake from scratch", "🎂"),
        ("Wine & cheese night", "🍷"),
        ("Try sushi for the first time", "🍣"),
        ("Master a pasta recipe", "🍝"),
        ("Coffee tasting at a café", "☕"),
        ("Make homemade ice cream", "🍦"),
        ("Try every chai stall on a street", "🍵"),
    ],
    "Experience": [
        ("Watch a sunrise together", "🌅"),
        ("Go to a live concert", "🎤"),
        ("Hot-air balloon ride", "🎈"),
        ("Stargazing on a clear night", "✨"),
        ("Take a dance class", "💃"),
        ("Visit a planetarium", "🪐"),
        ("Watch a Broadway / theatre show", "🎭"),
        ("Go on a cruise", "🚢"),
        ("Karaoke night", "🎤"),
        ("Try pottery making", "🏺"),
    ],
    "Life": [
        ("Buy our first home", "🏡"),
        ("Adopt a pet", "🐕"),
        ("Start a garden", "🌱"),
        ("Redecorate the bedroom", "🛏️"),
        ("Save ₹1 lakh together", "💰"),
        ("Start a couples' photo album", "📸"),
        ("Plan our 5-year dream", "🗺️"),
        ("Open a joint savings account", "🏦"),
        ("Make a vision board", "🖼️"),
    ],
    "Shopping": [
        ("Buy new shoes", "👟"),
        ("Buy matching outfits", "👕"),
        ("Get a new smartphone", "📱"),
        ("Buy a coffee machine", "☕"),
        ("New bedsheets & pillows", "🛏️"),
        ("Buy a smartwatch", "⌚"),
        ("Get sunglasses", "🕶️"),
        ("Buy a board game", "🎲"),
        ("Get a new bag", "👜"),
        ("Buy houseplants", "🪴"),
        ("New perfume / cologne", "🌸"),
        ("Get a Polaroid camera", "📷"),
        ("Buy a bicycle", "🚲"),
        ("Get matching rings", "💍"),
    ],
    "Gifts": [
        ("Surprise birthday gift", "🎁"),
        ("Anniversary present", "💐"),
        ("Handmade gift exchange", "✂️"),
        ("Send flowers for no reason", "🌹"),
        ("A care package when sick", "🧸"),
        ("Personalized photo frame", "🖼️"),
        ("Mystery box swap", "📦"),
    ],
    "Learning": [
        ("Learn a new language together", "🗣️"),
        ("Build a personal library", "📚"),
        ("Take an online course together", "💻"),
        ("Learn to play an instrument", "🎸"),
        ("Master a new recipe each month", "👨‍🍳"),
        ("Read 12 books in a year", "📖"),
        ("Learn photography basics", "📷"),
        ("Try chess matches every weekend", "♟️"),
    ],
    "Health": [
        ("Start a couples' workout routine", "🏋️"),
        ("Try yoga for 30 days", "🧘"),
        ("Meal-prep Sundays for a month", "🥗"),
        ("Walk 10,000 steps daily", "🚶"),
        ("Cook only home food for a month", "🍲"),
        ("8 hours of sleep for 2 weeks", "😴"),
        ("Drink 3L water daily", "💧"),
        ("Quit a bad habit together", "🚭"),
    ],
    "Challenges": [
        ("Run a 5K together", "🏃"),
        ("Hike a mountain", "🥾"),
        ("Learn to swim", "🏊"),
        ("30-day fitness challenge", "💪"),
        ("Read 12 books in a year", "📖"),
        ("Do a digital detox weekend", "📵"),
        ("Wake up at 5am for a week", "⏰"),
        ("Try yoga for 30 days", "🧘"),
        ("Cycle 50km in one ride", "🚴"),
        ("No-sugar month", "🚫"),
    ],
    "Romance": [
        ("Recreate our first date", "💌"),
        ("Write love letters to each other", "💕"),
        ("Slow dance in the kitchen", "💃"),
        ("Surprise picnic in the park", "🧺"),
        ("Watch the sunset on a beach", "🌇"),
        ("Candlelit dinner at home", "🕯️"),
        ("Take a couple's photoshoot", "📷"),
        ("Plan a surprise weekend", "🎁"),
        ("Movie marathon under blankets", "🎬"),
        ("Stargaze on the rooftop", "🌠"),
    ],
}
